#!/usr/bin/env python3
"""Generate static HTML pages from data files."""

from __future__ import annotations

import argparse
import json
import sys
from html import escape
from pathlib import Path


DATA_FILE = Path("data/site.json")
GENERATED_MARKER = "<!-- Generated by scripts/generate_site.py; edit data/site.json instead. -->"
PAGES = {
    Path("templates/index.html"): Path("index.html"),
    Path("templates/gallery.html"): Path("gallery.html"),
}


def attr(value: str) -> str:
    return escape(value, quote=True)


def title_attr(value: str) -> str:
    return value.replace('"', "&quot;")


def render_link(href: str, label: str, class_name: str | None = None) -> str:
    class_attr = f' class="{attr(class_name)}"' if class_name else ""
    return f'<a href="{attr(href)}"{class_attr}>{escape(label, quote=False)}</a>'


def render_download_link(href: str, label: str) -> str:
    return render_link(href, label, "button icon solid fa-download")


def render_notes(notes: list[dict[str, str]]) -> str:
    return "\n\n".join(
        f'\t\t\t\t\t{render_download_link(note["href"], note["label"])}' for note in notes
    )


def render_music_profiles(profiles: list[dict[str, str]]) -> str:
    return "\n".join(
        f'\t\t\t\t<li>{render_link(profile["href"], profile["label"])}</li>' for profile in profiles
    )


def render_download_items(items: list[dict[str, object]]) -> str:
    rendered: list[str] = []
    for item in items:
        links = item["links"]
        if not isinstance(links, list):
            raise TypeError("download item links must be a list")

        link_html = [
            render_download_link(str(link["href"]), str(link["label"])) for link in links
        ]
        if len(link_html) == 1:
            rendered.append(f"\t\t\t\t<li>{link_html[0]}</li>")
            continue

        first, *rest = link_html
        rest_html = "\n".join(f"\t\t\t\t\t{link}" for link in rest)
        rendered.append(f"\t\t\t\t<li>{first}\n{rest_html}\n\t\t\t\t</li>")
    return "\n\n".join(rendered)


def render_gallery(items: list[dict[str, object]]) -> str:
    rendered: list[str] = []
    for item in items:
        dimensions = ""
        width = item.get("width")
        height = item.get("height")
        if width and height:
            dimensions = f' width="{attr(str(width))}" height="{attr(str(height))}"'

        rendered.append(
            "\n".join(
                [
                    '\t\t\t\t<div class="masonry-item">',
                    (
                        f'\t\t\t\t\t<a href="{attr(str(item["href"]))}" data-lightbox="gallery" '
                        f'data-title="{title_attr(str(item["title_html"]))}" class="image fit">'
                    ),
                    "",
                    (
                        f'\t\t\t\t\t\t<img src="{attr(str(item["thumbnail"]))}"{dimensions} '
                        f'alt="{attr(str(item["alt"]))}" />'
                    ),
                    "\t\t\t\t\t</a>",
                    "\t\t\t\t</div>",
                ]
            )
        )
    return "\n\n".join(rendered)


def render_template(template: str, data: dict[str, object]) -> str:
    replacements = {
        "{{ generated_marker }}": GENERATED_MARKER,
        "{{ notes }}": render_notes(data["notes"]),
        "{{ music_profiles }}": render_music_profiles(data["music_profiles"]),
        "{{ off_vocals }}": render_download_items(data["off_vocals"]),
        "{{ tabs }}": render_download_items(data["tabs"]),
        "{{ gallery_items }}": render_gallery(data["gallery"]),
    }

    rendered = template
    for placeholder, value in replacements.items():
        rendered = rendered.replace(placeholder, value)

    leftovers = [placeholder for placeholder in replacements if placeholder in rendered]
    if leftovers:
        raise RuntimeError(f"unrendered placeholders: {', '.join(leftovers)}")

    return rendered


def load_data() -> dict[str, object]:
    return json.loads(DATA_FILE.read_text(encoding="utf-8"))


def generate() -> dict[Path, str]:
    data = load_data()
    return {
        output: render_template(template.read_text(encoding="utf-8"), data)
        for template, output in PAGES.items()
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate static pages from data/site.json.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale.")
    args = parser.parse_args()

    generated = generate()
    stale: list[Path] = []
    for output, content in generated.items():
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != content:
                stale.append(output)
            continue

        output.write_text(content, encoding="utf-8")

    if stale:
        for output in stale:
            print(f"{output} is out of date")
        return 1

    if args.check:
        print("Generated pages are up to date.")
    else:
        print("Generated index.html and gallery.html.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
