#!/usr/bin/env python3
"""Validate static GitHub Pages assets before publishing."""

from __future__ import annotations

import argparse
import subprocess
import sys
import unicodedata
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit


HTML_FILES = (Path("index.html"), Path("gallery.html"))
GENERATED_FILES = (Path("index.html"), Path("gallery.html"))
GENERATED_MARKER = "<!-- Generated by scripts/generate_site.py; edit data/site.json instead. -->"


class LinkParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.links: list[tuple[str, str]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        for name, value in attrs:
            if name in {"href", "src"} and value:
                self.links.append((name, value))


def run_git(args: list[str]) -> list[str]:
    result = subprocess.run(
        ["git", "-c", "core.quotePath=false", *args],
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    return result.stdout.splitlines()


def tracked_files() -> set[str]:
    return {path for path in run_git(["ls-files"]) if Path(path).exists()}


def is_local_url(url: str) -> bool:
    parsed = urlsplit(url)
    return not parsed.scheme and not parsed.netloc and not url.startswith(("mailto:", "#"))


def local_path(url: str) -> str:
    path = urlsplit(url).path
    return unquote(path)


def validate_links(files: set[str]) -> list[str]:
    errors: list[str] = []
    for html_file in HTML_FILES:
        parser = LinkParser()
        parser.feed(html_file.read_text(encoding="utf-8"))
        for attr, url in parser.links:
            if not is_local_url(url):
                continue

            path = local_path(url)
            if not path or path.endswith("/"):
                continue

            if unicodedata.normalize("NFC", path) != path:
                errors.append(f"{html_file}: {attr}={url!r} is not NFC-normalized")

            if path not in files:
                errors.append(f"{html_file}: {attr}={url!r} does not match a tracked file exactly")
    return errors


def validate_ds_store(files: set[str]) -> list[str]:
    return [f"{path}: .DS_Store must not be tracked" for path in sorted(files) if path.endswith(".DS_Store")]


def validate_robots(files: set[str]) -> list[str]:
    robots = Path("robots.txt")
    if "robots.txt" not in files and robots.exists():
        return ["robots.txt exists but is untracked; remove it or commit an intentional crawler policy"]

    if not robots.exists():
        return []

    content = robots.read_text(encoding="utf-8")
    if "Disallow: /" in content:
        return ["robots.txt blocks all crawlers with 'Disallow: /'"]
    return []


def validate_generated_markers() -> list[str]:
    errors: list[str] = []
    for path in GENERATED_FILES:
        content = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in content:
            errors.append(f"{path}: missing generated marker")
    return errors


def validate_generated_freshness() -> list[str]:
    result = subprocess.run(
        [sys.executable, "scripts/generate_site.py", "--check"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode == 0:
        return []

    output = "\n".join(part for part in (result.stdout, result.stderr) if part.strip())
    return [f"generated pages are out of date:\n{output.strip()}"]


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate static site paths and generated output.")
    parser.add_argument("--skip-generated", action="store_true", help="Skip generator freshness checks.")
    args = parser.parse_args()

    files = tracked_files()
    errors = [
        *validate_links(files),
        *validate_ds_store(files),
        *validate_robots(files),
    ]

    if not args.skip_generated:
        errors.extend(validate_generated_markers())
        errors.extend(validate_generated_freshness())

    if errors:
        print("Static site validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1

    print("Static site validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
