#!/usr/bin/env python3
"""Validate static GitHub Pages assets before publishing."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import unicodedata
import xml.etree.ElementTree as ET
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit


HTML_FILES = (Path("index.html"), Path("gallery.html"))
GENERATED_FILES = (Path("index.html"), Path("gallery.html"))
GENERATED_MARKER = "<!-- Generated by scripts/generate_site.py; edit data/*.json instead. -->"
EXPECTED_URLS = {"https://v2ark.com/", "https://v2ark.com/gallery.html"}
EXPECTED_DISALLOW_PATHS = {
    "/assets/lightbox/images/",
    "/assets/logo/",
    "/assets/webfonts/",
    "/files/",
    "/gallery/",
    "/images/",
    "/music/",
    "/notes/",
    "/tabs/",
}


class LinkParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.links: list[tuple[str, str]] = []
        self.anchors: list[dict[str, str]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_map = {name: value for name, value in attrs if value is not None}
        if tag == "a":
            self.anchors.append(attr_map)

        for name, value in attrs:
            if name in {"href", "src", "data-file"} and value:
                self.links.append((name, value))


def run_git(args: list[str]) -> list[str]:
    result = subprocess.run(
        ["git", "-c", "core.quotePath=false", *args],
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    return result.stdout.splitlines()


def tracked_files() -> set[str]:
    return set(run_git(["ls-files"]))


def repository_files() -> set[str]:
    return tracked_files() | set(run_git(["ls-files", "--others", "--exclude-standard"]))


def is_local_url(url: str) -> bool:
    parsed = urlsplit(url)
    return not parsed.scheme and not parsed.netloc and not url.startswith(("mailto:", "#"))


def local_path(url: str) -> str:
    path = urlsplit(url).path
    return unquote(path)


def validate_links(files: set[str]) -> list[str]:
    errors: list[str] = []
    for html_file in HTML_FILES:
        parser = LinkParser()
        parser.feed(html_file.read_text(encoding="utf-8"))
        for attr, url in parser.links:
            if not is_local_url(url):
                continue

            path = local_path(url)
            if not path or path.endswith("/"):
                continue

            if unicodedata.normalize("NFC", path) != path:
                errors.append(f"{html_file}: {attr}={url!r} is not NFC-normalized")

            if path not in files:
                errors.append(f"{html_file}: {attr}={url!r} does not match a tracked file exactly")
    return errors


def validate_asset_discovery() -> list[str]:
    errors: list[str] = []
    site = json.loads(Path("data/site.json").read_text(encoding="utf-8"))
    resume_path = str(site["resume_path"])
    for html_file in HTML_FILES:
        parser = LinkParser()
        parser.feed(html_file.read_text(encoding="utf-8"))

        for anchor in parser.anchors:
            href = anchor.get("href")
            if not href or not is_local_url(href):
                continue

            path = local_path(href)
            if path == resume_path:
                errors.append(f"{html_file}: resume must use data-file, not a crawlable href")

            if any(path.startswith(prefix.lstrip("/")) for prefix in EXPECTED_DISALLOW_PATHS):
                rel_values = set(anchor.get("rel", "").split())
                if "nofollow" not in rel_values:
                    errors.append(f"{html_file}: {href!r} must use rel=\"nofollow\"")
    return errors


def validate_ds_store(files: set[str]) -> list[str]:
    return [f"{path}: .DS_Store must not be tracked" for path in sorted(files) if path.endswith(".DS_Store")]


def validate_robots() -> list[str]:
    robots = Path("robots.txt")
    if not robots.exists():
        return ["robots.txt is missing"]

    content = robots.read_text(encoding="utf-8")
    lines = {line.strip() for line in content.splitlines()}
    errors: list[str] = []
    if "Disallow: /" in lines:
        errors.append("robots.txt blocks all crawlers with 'Disallow: /'")
    if "Allow: /" not in content:
        errors.append("robots.txt does not explicitly allow crawlers")
    if "Sitemap: https://v2ark.com/sitemap.xml" not in content:
        errors.append("robots.txt does not reference the canonical sitemap")
    disallow_paths = {
        line.removeprefix("Disallow: ").strip()
        for line in lines
        if line.startswith("Disallow: ")
    }
    if disallow_paths != EXPECTED_DISALLOW_PATHS:
        errors.append(
            f"robots.txt disallows {sorted(disallow_paths)}, expected {sorted(EXPECTED_DISALLOW_PATHS)}"
        )
    return errors


def validate_sitemap() -> list[str]:
    sitemap = Path("sitemap.xml")
    if not sitemap.exists():
        return ["sitemap.xml is missing"]

    try:
        tree = ET.parse(sitemap)
    except ET.ParseError as error:
        return [f"sitemap.xml is not valid XML: {error}"]

    namespace = {"sitemap": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    urls = {
        loc.text
        for loc in tree.findall(".//sitemap:loc", namespace)
        if loc.text is not None
    }
    if urls != EXPECTED_URLS:
        return [f"sitemap.xml URLs are {sorted(urls)}, expected {sorted(EXPECTED_URLS)}"]
    return []


def validate_generated_markers() -> list[str]:
    errors: list[str] = []
    for path in GENERATED_FILES:
        content = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in content:
            errors.append(f"{path}: missing generated marker")
    return errors


def validate_generated_freshness() -> list[str]:
    result = subprocess.run(
        [sys.executable, "scripts/generate_site.py", "--check"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode == 0:
        return []

    output = "\n".join(part for part in (result.stdout, result.stderr) if part.strip())
    return [f"generated pages are out of date:\n{output.strip()}"]


def validate_thumbnails() -> list[str]:
    result = subprocess.run(
        [sys.executable, "scripts/audit_thumbnails.py"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if result.returncode == 0:
        return []

    output = "\n".join(part for part in (result.stdout, result.stderr) if part.strip())
    return [f"thumbnail audit failed:\n{output.strip()}"]


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate static site paths and generated output.")
    parser.add_argument("--skip-generated", action="store_true", help="Skip generator freshness checks.")
    args = parser.parse_args()

    files = repository_files()
    tracked = tracked_files()
    errors = [
        *validate_links(files),
        *validate_asset_discovery(),
        *validate_ds_store(tracked),
        *validate_robots(),
        *validate_sitemap(),
    ]

    if not args.skip_generated:
        errors.extend(validate_generated_markers())
        errors.extend(validate_generated_freshness())
        errors.extend(validate_thumbnails())

    if errors:
        print("Static site validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1

    print("Static site validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
